handle older XML API error shapes
Some older XML APIs like S3 have error shapes that don't actually have
any members nor an Error field with information about the HTTP status
code. Instead, they are just named shapes with no members and an
exception: true field. We need to handle these by just putting them into
a generic 400 status code bucket unfortunately.